{{ 
    config(
        materialized='table'
    ) 
}}

with source as (
    SELECT 
        BOOKING_ID,
        CLIENT_ID,
        SERVICE_ID,
        CAST(BOOKING_DATE AS DATE) AS BOOKING_DATE,
        CAST(BOOKING_TIME AS TIME) AS BOOKING_TIME,
        CAST(BOOKING_DATE || ' ' || BOOKING_TIME AS TIMESTAMP) AS BOOKING_TIMESTAMP, 
        DENTIST_ID,
        METADATA_FILENAME,
        METADATA_FILE_ROW_NUMBER,
        METADATA_FILE_LAST_MODIFIED 
    FROM {{ source("AZURE_BLOB_DENTAL", "BOOKINGS")}}
)

SELECT 
    BOOKING_ID,
    CLIENT_ID,
    SERVICE_ID,
    BOOKING_DATE,
    BOOKING_TIME,
    BOOKING_TIMESTAMP, 
    DENTIST_ID,
    METADATA_FILENAME,
    METADATA_FILE_ROW_NUMBER,
    METADATA_FILE_LAST_MODIFIED
FROM source